In [1]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
v

[0.5, 0.75, 1.0, 1.5, 2.0]

In [2]:
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [3]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [4]:
m[1][0]

0.5

In [5]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [6]:
import array
v = [0.5, 0.75, 1.0, 1.5, 2.0]
a = array.array('f', v)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0])

In [7]:
a.append(0.5)
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5])

In [8]:
a.extend([5.0, 6.75])
a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [9]:
2 * a

array('f', [0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75, 0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75])

In [10]:
a.tolist()

[0.5, 0.75, 1.0, 1.5, 2.0, 0.5, 5.0, 6.75]

In [11]:
type(a)

array.array

In [12]:
import numpy as np
a = np.array([0, 0.5, 1.0, 1.5, 2.0])
a

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
type(a)

numpy.ndarray

In [14]:
b = np.array(['a', 'b', 'c'])
b

array(['a', 'b', 'c'], dtype='<U1')

In [15]:
type(b)

numpy.ndarray

In [16]:
c = np.arange(2, 20,2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
d = np.arange(8, dtype=np.float)
d

<ipython-input-17-e4c40218d7c0>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  d = np.arange(8, dtype=np.float)


array([0., 1., 2., 3., 4., 5., 6., 7.])

In [18]:
d[5:]

array([5., 6., 7.])

In [19]:
d[:2]

array([0., 1.])

In [20]:
d.sum()

28.0

In [21]:
d.std()

2.29128784747792

In [22]:
d.cumsum()

array([ 0.,  1.,  3.,  6., 10., 15., 21., 28.])

In [23]:
d.mean()

3.5

In [25]:
l = [0., 0.5, 1.5, 3., 5.]
2 * l

[0.0, 0.5, 1.5, 3.0, 5.0, 0.0, 0.5, 1.5, 3.0, 5.0]

2 * d

In [26]:
2*d

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [27]:
d ** 2

array([ 0.,  1.,  4.,  9., 16., 25., 36., 49.])

In [28]:
2 ** d

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128.])

In [29]:
d ** d


array([1.00000e+00, 1.00000e+00, 4.00000e+00, 2.70000e+01, 2.56000e+02,
       3.12500e+03, 4.66560e+04, 8.23543e+05])

In [30]:
np.exp(d)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03])

In [31]:
np.sqrt(d)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131])

In [32]:
np.sqrt(2.5)

1.5811388300841898

In [33]:
import math
math.sqrt(2.5)

1.5811388300841898

In [34]:
import math
math.sqrt(4)
# only works for one number (doesn't work for d)

2.0

In [36]:
e = np.array([d, d * 2])
e
# one row is d and the other row is d*2

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.]])

In [37]:
e[0]
# this is to select the first row

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [38]:
e[0,2]
# this is to select this first line second column

2.0

In [39]:
e[:, 1]
# first column

array([1., 2.])

In [40]:
e.sum()
# calculates the sum of all values

84.0

In [41]:
e.sum(axis=0)
# Calculates the sum along the first axis; i.e., column-wise

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21.])

In [42]:
e.sum(axis=1)
# Calculates the sum along the second axis; i.e., row-wise

array([28., 56.])

In [43]:
f = np.zeros((2, 3), dtype = 'i')
f

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [44]:
g = np.ones((2,3),dtype = 'i')
g

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [46]:
g * 20
# if you want all 20s (but you need to create the ones before)

array([[20, 20, 20],
       [20, 20, 20]], dtype=int32)

In [48]:
h = np.linspace(5, 15, 12)
h
# Creates a one-dimensional ndarray object with evenly spaced intervals between numbers; parameters used are start, end, and num (number of elements)
# Will be used very often
# It's not a range so it stops at 15 (and not 14 like before for a range)

array([ 5.        ,  5.90909091,  6.81818182,  7.72727273,  8.63636364,
        9.54545455, 10.45454545, 11.36363636, 12.27272727, 13.18181818,
       14.09090909, 15.        ])

In [49]:
h.size


12

In [51]:
h.ndim 
# The number of dimension

1

In [54]:
h.dtype
# The dtype of the elements
# 64 is the amount of bits you need to run it

dtype('float64')

In [53]:
g.ndim

2

In [67]:
c.shape
# The shape of c (it is 9 numbers on one line)

(9,)

In [56]:
np.shape(c)

(9,)

In [68]:
cr = c.reshape((3, 3))
cr
#This reshapes it in a 3 by 3 matrix

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [69]:
cr.T
#Make sure you use big T to transpose the matrix

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [70]:
cr.transpose()
# Same as big T to transpose

array([[ 2,  8, 14],
       [ 4, 10, 16],
       [ 6, 12, 18]])

In [72]:
np.resize(c, (3, 1))
# Resize: we only use the first 3 to resize into one column (the number in the resize column has to be smaller than the full size)

array([[2],
       [4],
       [6]])

In [73]:
np.resize(c, (1, 5))
# 1 row 5 columns

array([[ 2,  4,  6,  8, 10]])

In [74]:
np.resize(c, (2, 4))
# 2 rows 4 columns

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [63]:
crr = np.resize(c, (4, 2))
crr

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [75]:
np.hstack((crr, 2 * crr))
# Horizontal stack

array([[ 2,  4,  4,  8],
       [ 6,  8, 12, 16],
       [10, 12, 20, 24],
       [14, 16, 28, 32]])

In [65]:
np.vstack((crr, 0.5 * crr))

array([[ 2.,  4.],
       [ 6.,  8.],
       [10., 12.],
       [14., 16.],
       [ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [66]:
crr.flatten()

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [76]:

crr > 5

array([[False, False],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [77]:
(crr == 8).astype(int)

array([[0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [78]:
(crr > 4) & (crr <= 12)

array([[False, False],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [79]:
crr[crr > 8]

array([10, 12, 14, 16])

In [80]:
crr[(crr > 4) & (crr <= 12)]

array([ 6,  8, 10, 12])

In [83]:
crr[(crr < 4) | (crr >= 12)]
# | means or

array([ 2, 12, 14, 16])

In [84]:
np.where(crr % 2 == 0, 'even', 'odd')
# if it can devide by 2 then it is even

array([['even', 'even'],
       ['even', 'even'],
       ['even', 'even'],
       ['even', 'even']], dtype='<U4')

In [85]:
r = np.arange(12).reshape((4, 3))
s = np.arange(12).reshape((4, 3)) * 0.5

In [89]:
r
# 4 by 3 with 0 to 11

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [90]:
s
# 4 by 3 with 0 to 11 * 0.5

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ],
       [4.5, 5. , 5.5]])

In [88]:
r+s

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [91]:
s+r

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ],
       [13.5, 15. , 16.5]])

In [92]:

r.shape

(4, 3)

In [93]:
def f(x):
    return 3 * x + 5

In [94]:
f(0.5)

6.5

In [95]:
f(r)

array([[ 5,  8, 11],
       [14, 17, 20],
       [23, 26, 29],
       [32, 35, 38]])

In [96]:
x = np.random.standard_normal((1000000, 5))
y = 2 * x + 3
C = np.array((x, y), order='C')    # This creates a two-dimensional ndarray object with C order (row-major).
F = np.array((x, y), order='F')    # This creates a two-dimensional ndarray object with F order (column-major).
C[:2].round(2)

array([[[-0.07, -0.83, -1.2 , -0.21, -0.82],
        [-1.15, -0.31,  0.07, -0.3 , -1.15],
        [-0.21, -0.66,  1.44,  1.31, -1.1 ],
        ...,
        [-0.4 , -1.4 , -0.3 ,  0.82, -1.81],
        [ 0.49, -0.93,  0.44,  1.69, -0.01],
        [ 0.65, -1.77,  0.46, -0.26, -0.34]],

       [[ 2.86,  1.34,  0.61,  2.59,  1.35],
        [ 0.7 ,  2.39,  3.14,  2.41,  0.71],
        [ 2.58,  1.69,  5.88,  5.62,  0.81],
        ...,
        [ 2.2 ,  0.2 ,  2.41,  4.63, -0.61],
        [ 3.98,  1.15,  3.88,  6.37,  2.99],
        [ 4.3 , -0.53,  3.93,  2.49,  2.33]]])

In [99]:
%timeit C.sum()

1.97 ms ± 25.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [100]:
%timeit F.sum()

2.02 ms ± 62.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [101]:
import pandas as pd
df = pd.DataFrame([10, 20, 30, 40],
                  columns=['numbers'],
                  index=['a', 'b', 'c', 'd'])
df

numbers
a       10
b       20
c       30
d       40